version: "3.8"

services:
  # Development overrides
  api-1:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm ci || npm i && npm run dev"

  api-2:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm ci || npm i && npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm ci || npm i && npm run dev -- --host"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8080/api
    ports:
      - "3000:3000"

  # PostgreSQL with exposed ports for debugging
  postgres:
    ports:
      - "5432:5432"

  # Redis with exposed ports for debugging
  redis:
    ports:
      - "6379:6379"
